version: "3.9"
services:
  pg:
    image: postgres:16
    container_name: bronze_pg
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"           # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse"]
      interval: 3s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
