[project]
name = "bronze-hash-pg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "polars>=1.5.0",
  "pandas>=2.2",
  "pydantic>=2.7",
  "pydantic-settings>=2.2",
  "sqlalchemy>=2.0",
  "psycopg2-binary>=2.9",
]
